from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class TvState(Protocol):
    power_state: dict[str, Any]
    current_app_id: str | None
    sound_output: str | None
    muted: bool | None
    volume: int | None
    apps: dict[str, Any]
    inputs: dict[str, Any]
    is_on: bool
    is_screen_on: bool


class TvClient(Protocol):
    client_key: str | None
    tv_state: TvState

    async def connect(self) -> bool: ...
    async def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...
    def is_registered(self) -> bool: ...
    async def register_state_update_callback(
        self, callback: Callable[[TvState], Awaitable[None]]
    ) -> None: ...
    def unregister_state_update_callback(
        self, callback: Callable[[TvState], Awaitable[None]]
    ) -> None: ...
    def clear_state_update_callbacks(self) -> None: ...
    async def power_off(self) -> None: ...
    async def power_on(self) -> dict[str, Any]: ...
    async def launch_app(self, app: str) -> dict[str, Any]: ...
    async def set_volume(self, volume: int) -> dict[str, Any]: ...
    async def volume_up(self) -> dict[str, Any]: ...
    async def volume_down(self) -> dict[str, Any]: ...
    async def set_mute(self, mute: bool) -> dict[str, Any]: ...
    async def get_apps(self) -> dict[str, Any] | None: ...
    async def get_inputs(self) -> dict[str, Any] | None: ...
    async def button(self, name: str) -> None: ...
    async def play(self) -> dict[str, Any]: ...
    async def pause(self) -> dict[str, Any]: ...
    async def stop(self) -> dict[str, Any]: ...
    async def rewind(self) -> dict[str, Any]: ...
    async def fast_forward(self) -> dict[str, Any]: ...
    async def set_input(self, input_id: str) -> dict[str, Any]: ...
    async def send_message(
        self, message: str, icon_path: str | None = None
    ) -> dict[str, Any]: ...
    async def request(
        self, uri: str, payload: dict[str, Any] | None = None, **kwargs: Any
    ) -> dict[str, Any]: ...
